name: Terraform Deployment

on:
  push:
    branches:
      - new1  # Automatically triggers on push to 'new1' branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      WORKING_DIR: ./terraform

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.0"

    - name: Initialize Terraform
      working-directory: ${{ env.WORKING_DIR }}
